# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: ferryhinardi
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Jakarta
          
          # Plugin: isocalendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          # Plugin: languages
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_limit: 8
          plugin_languages_threshold: 0%
          plugin_languages_colors: github
          plugin_languages_sections: most-used
          plugin_languages_indepth: no
          plugin_languages_analysis_timeout: 20
          plugin_languages_categories: markup, programming
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_load: 300
          plugin_languages_recent_days: 14
          
          # Plugin: stars
          plugin_stars: yes
          plugin_stars_limit: 4
          
          # Plugin: activity
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_days: 14
          plugin_activity_visibility: all
          plugin_activity_timestamps: no
          plugin_activity_filter: all
          
          # Plugin: lines
          plugin_lines: yes
          
          # Plugin: introduction
          plugin_introduction: yes
          plugin_introduction_title: yes
          
          # Plugin: gists
          plugin_gists: yes
